feature-team1ticket007
Ditmar/plagiarist-g1 pull request #2
Opened 2022-12-11 21:55 UTC by JamesJose15

New feature add ticket007

2022-12-14 02:51 UTC, Ditmar commented
Nice work @JamesJose15 , only a few comments please review that and your pr will be merged to the master branch

2022-12-14 02:51 UTC, Ditmar commented
Something more is neceary to rebase the pr 
`
please rebase your dev-branches
if you don't remember how do merge. 
you can use 
in the master branch 
git pull origin master 
change to your feat branch
git rebase -X ours master
after that is necessary to push the changes in the remote branch
for that you can use
git push -f
`

2022-12-14 20:58 UTC, JamesJose15 commented
@Ditmar already fixed the conflicts I had, could you review my ticket please

2022-12-15 04:03 UTC, Ditmar requested changes

2022-12-15 04:03 UTC, Ditmar commented on src/components/UploadComponent/ItemUpload/itemUpload.styles.js
> +        padding: '10px',
use rem instead pixel units

2022-12-15 04:03 UTC, Ditmar commented on src/components/UploadComponent/index.jsx
> +//import ItemUpload from "./ItemUpload"
remote the comment

2022-12-15 04:03 UTC, Ditmar commented on src/components/UploadComponent/FileUpload/index.jsx
> +        alert(upload.file.name)
Why do you use an alert here that is not part of the scope of the ticket

2022-12-15 04:03 UTC, Ditmar commented on src/components/UploadComponent/FileUpload/index.jsx
> +                <PictureAsPdf style={{ color: 'orange' , width: "50px", height:"50px" }} /> <br/> {upload.file.name}  <br/>  {upload.file.type} <br/> {upload.file.size} MB
The color needs to come from the palette of colors from here https://github.com/Ditmar/plagiarist-g1/blob/master/src/theme/theme.js 
you can access to the color using the styles.

2022-12-15 04:03 UTC, Ditmar commented on src/components/UploadComponent/FileUpload/fileUpload.styles.js
> +        background:"#239f98",
Please don't hardcode the colors, use the theme.
`theme.palette.fourth.main`
This is only an example, you can edit the file https://github.com/Ditmar/plagiarist-g1/blob/master/src/theme/theme.js 
and add the colors that you need.

2022-12-15 04:03 UTC, Ditmar approved these changes

2022-12-15 04:03 UTC, merged